name: Build & Deploy

on:
    # workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            PORT: ${{ vars.PORT }}
            REQUEST_TIMEOUT_MS: ${{ vars.REQUEST_TIMEOUT_MS }}
            CHECK_RETENTION_PER_MONITOR: ${{ vars.CHECK_RETENTION_PER_MONITOR }}
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: "ap-southeast-2"
            
            - name: Setup
              uses: hashicorp/setup-terraform@v3
        
            - name: Launch AWS Infrastructure
              run: |
                terraform init
                terraform validate
                terraform plan
                terraform apply -auto-approve
              working-directory: ./terraform
            
            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
        
            - name: Build & Push to ECR
              run: |
                FRONTEND_URI=${{ secrets.AWS_ACCOUNT_ID  }}.dkr.ecr.ap-southeast-2.amazonaws.com/frontend-ecr:latest
                BACKEND_URI=${{ secrets.AWS_ACCOUNT_ID  }}.dkr.ecr.ap-southeast-2.amazonaws.com/backend-ecr:latest

                docker build -t $FRONTEND_URI ./client
                docker build -t $BACKEND_URI .

                docker push $FRONTEND_URI
                docker push $BACKEND_URI

            - name: Deploy Services to ECS
              run: |
                for SERVICE in backend-service frontend-service
                do
                  aws ecs update-service --cluster pulsecheck-cluster --service $SERVICE --force-new-deployment
                done
               



